# Usa la imagen de Node.js 22.7.0
FROM node:22.7.0

# Establecer el directorio de trabajo en /app dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json (si tienes) al contenedor
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar el resto del código fuente al contenedor
COPY . .

# Exponer el puerto 3000 (ajústalo según lo que uses en tu aplicación)
EXPOSE 8030

# Comando para iniciar la aplicación (usa el comando del package.json)
CMD ["npm", "start"]